### PR TITLE
Update for 10.6

### PR DESCRIPTION
**Pull request by jf990**
Address #1 update for 10.6 core and updated test.

for https://github.com/highlightjs/highlight.js/issues/3008

@joshgoebel can someone take a look and review this?

### CODE REVIEW

**Comment by jf990** [comment]
missing .gitinore

**Comment by joshgoebel** [comment]
I'd recommend using our build process.  If you insist on doing it yourself then you will need a secondary file that you build that wraps the registration... the distributable purposely is supposed to include the registerLanguage call itself.  Look at the example of robots-txt:

```
hljs.registerLanguage("robots-txt",(function(e){var s=e.COMMENT("#","$");return{aliases:["robotstxt","robots.txt"],case_insensitive:!0,lexemes:"[a-z-]+",keywo...
```

IE, all someone has to do is include the `<script>` tag, nothing else.  That's the goal.

**Comment by jf990** [comment]
@joshgoebel where's the doc that explain how I should build the `dist`? I don't see how that was done for robots.

**Comment by joshgoebel** [comment]
https://github.com/highlightjs/highlight.js/blob/master/extra/3RD_PARTY_QUICK_START.md

You checkout/put your repo under `extra` and then just build Highlight.js (node) and it will build your grammar and put the file in `dist` for you.

**Pull request closed without merging**
